export const GET_REGISTER_REQUEST = "GET_REGISTER_REQUEST";
export const GET_REGISTER_ERROR = "GET_REGISTER_ERROR";
export const GET_REGISTER_SUCCESS = "GET_REGISTER_SUCCESS";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const GET_INFO_SUCCESS = "GET_INFO_SUCCESS";
export const GET_INFO_REQUEST = "GET_INFO_REQUEST";
export const GET_INFO_ERROR = "GET_INFO_ERROR";

export const UPDATE_INFO_ERROR = "UPDATE_INFO_ERROR";
export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS";
export const UPDATE_INFO_REQUEST = "UPDATE_INFO_REQUEST";

export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";